# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem 'activerecord', '~> 5.2.3', :require => 'active_record'
gem 'rake'
gem 'require_all'
gem 'sqlite3', '~>1.3.6'
gem 'pry'
gem 'sinatra-activerecord', :require => 'sinatra/activerecord'
gem 'rspec'
gem 'faker', :git => 'https://github.com/faker-ruby/faker.git', :branch => 'master'