# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# gem "rails"

gem 'pry'

gem 'sqlite3'

gem 'uuid', '~> 2.3', '>= 2.3.8'

gem 'require_all'

gem 'json'