# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

# gem "rails"
gem "sinatra"
gem "require_all"
gem "activerecord"
gem "sinatra-activerecord"
gem "pry"
gem "shotgun"
gem "rest-client"
gem "sqlite3"
